In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# now let's concatenate using pandas

In [9]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [10]:
ser1

T    0
U    1
V    2
dtype: int64

In [11]:
ser2

X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [14]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [15]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['x','y','z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['y','q','z'])

In [16]:
dframe1

x         y         z
0  0.143895 -0.829155  0.341524
1  1.932087 -0.116028 -0.437225
2 -0.362037  0.613033 -0.551872
3 -0.371514  0.746358  0.951311

In [17]:
dframe2

y         q         z
0  1.343913  0.801510 -0.022965
1 -0.606954 -0.833549  0.284279
2 -1.399072 -0.766762 -0.996627

In [19]:
pd.concat([dframe1,dframe2])

q         x         y         z
0       NaN  0.143895 -0.829155  0.341524
1       NaN  1.932087 -0.116028 -0.437225
2       NaN -0.362037  0.613033 -0.551872
3       NaN -0.371514  0.746358  0.951311
0  0.801510       NaN  1.343913 -0.022965
1 -0.833549       NaN -0.606954  0.284279
2 -0.766762       NaN -1.399072 -0.996627

In [20]:
pd.concat([dframe1,dframe2],ignore_index=True)

q         x         y         z
0       NaN  0.143895 -0.829155  0.341524
1       NaN  1.932087 -0.116028 -0.437225
2       NaN -0.362037  0.613033 -0.551872
3       NaN -0.371514  0.746358  0.951311
4  0.801510       NaN  1.343913 -0.022965
5 -0.833549       NaN -0.606954  0.284279
6 -0.766762       NaN -1.399072 -0.996627