In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Universal functions are the basic functions that you can apply to every value in an array

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.68428293,  0.38488157,  0.16749924, -2.38443057, -1.03176961,
       -0.08691784, -0.60004028,  0.94224235, -2.37584281,  0.51698339])

In [7]:
B = np.random.randn(10)
B

array([-0.47710762, -2.4203866 ,  1.73093488, -0.23567228,  1.26203335,
        1.63900792, -0.91787263,  1.25025581, -0.74949658, -0.58556533])

In [8]:
# Binary Functions
np.add(A,B)

array([-1.16139055, -2.03550503,  1.89843412, -2.62010285,  0.23026374,
        1.55209008, -1.51791291,  2.19249816, -3.12533939, -0.06858194])

In [9]:
#Find max or min between 2 arrays
np.maximum(A,B)

array([-0.47710762,  0.38488157,  1.73093488, -0.23567228,  1.26203335,
        1.63900792, -0.60004028,  1.25025581, -0.74949658,  0.51698339])

In [15]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True