In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2.shape

(2L, 4L)

In [11]:
my_array2.dtype

dtype('int32')

In [12]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
int(np.zeros(5))

TypeError: only length-1 arrays can be converted to Python scalars

In [17]:
my_zeros_array = np.zeros(5)

In [18]:
my_zeros_array.dtype

dtype('float64')

In [19]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.empty(5)

array([  3.49937448e-316,   3.49937448e-316,   1.86999539e-316,
         3.49940768e-316,   1.86305989e-316])

In [21]:
my_empty_arrya = np.empty(5)

In [22]:
my_empty_arrya.dtype

dtype('float64')

In [23]:
my_empty_array_1 = int(np.empty(5))

TypeError: only length-1 arrays can be converted to Python scalars

In [24]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arrange(5)

AttributeError: 'module' object has no attribute 'arrange'

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])